### ISSUE TITLE
VS Code Zotero extension

### ISSUE THREAD

**Issue by mblode** [michaelaye/planetpy#4]
Hey @michaelaye,
I wanted to reach out but I couldn't find a simple way to get in contact with you.
I've created a VS Code extension that solves your Zotero Better Bibtex issue with VS Code as raised here: https://github.com/Microsoft/vscode/issues/41316

Please let me know if this solves your issue or if you have other feedback. Thank you :)

https://marketplace.visualstudio.com/items?itemName=mblode.zotero

**Comment by michaelaye** [comment]
Hey thank you! I will definitely check it out! Even so, currently I'm more on the paperpile track, hoping they will add something like that as well soon.
